#!/bin/bash

USERNAME=$(whoami)
DATETIME=$(date)
HOSTNAME=$(hostname)
OS=$(source /etc/os-release && echo "$PRETTY_NAME")
UPTIME=$(uptime -p)

CPU=$(lshw -class processor | grep 'product' | awk -F ': ' '{print $2}')
RAM=$(free -h | awk '/^Mem:/ {print $2}')
DISKS=$(lsblk -o MODEL,SIZE | tail -n +2)
VIDEO=$(lshw -class display | grep 'product' | awk -F ': ' '{print $2}')

FQDN=$(hostname -f)
IP_ADDRESS=$(ip -4 a show scope global | grep inet | awk '{print $2}' | cut -d/ -f1)
GATEWAY=$(ip r | grep default | awk '{print $3}')
DNS_SERVER=$(grep "^nameserver" /etc/resolv.conf | awk '{print $2}' | paste -sd ', ')

LOGGED_IN_USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd ', ')
DISK_SPACE=$(df -h --output=target,avail | tail -n +2)
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(uptime | awk -F 'load average: ' '{print $2}')
LISTENING_PORTS=$(ss -tuln | awk 'NR>1 {print $5}' | cut -d: -f2 | sort -nu | paste -sd ', ')
UFW_STATUS=$(sudo ufw status | grep -oE 'Status: (active|inactive)' | awk '{print $2}')

cat <<EOF

System Report generated by $USERNAME, $DATETIME

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU
RAM: $RAM
Disks:
$DISKS
Video: $VIDEO

Network Information
-------------------
FQDN: $FQDN
Host Address: $IP_ADDRESS
Gateway IP: $GATEWAY
DNS Server: $DNS_SERVER

System Status
-------------
Users Logged In: $LOGGED_IN_USERS
Disk Space:
$DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Listening Network Ports: $LISTENING_PORTS
UFW Status: $UFW_STATUS

EOF
